server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: icecreamorder
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
        - id: store
          uri: http://localhost:8082
          predicates:
            - Path=/saleses/**
        - id: pay
          uri: http://localhost:8083
          predicates:
            - Path=/paymentInformations/**
        - id: storesales
          uri: http://localhost:8084
          predicates:
            - Path=/storeSalesViews/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: icecreampickup-icecreamorder
          uri: http://icecreamorder:8080
          predicates:
            - Path=/orders/**
        - id: icecreampickup-store
          uri: http://store:8080
          predicates:
            - Path=/saleses/**
        - id: icecreampickup-pay
          uri: http://pay:8080
          predicates:
            - Path=/paymentInformations/**
        - id: icecreampickup-storesales
          uri: http://storesales:8080
          predicates:
            - Path=/storeSalesViews/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
